# Dockerfile
FROM node:18-alpine

# Mendefinisikan build argument
ARG NEXT_PUBLIC_BACKEND_API_BASEURL
ARG NEXT_PUBLIC_URL_PARAM_ENCRYPT_KEY
ARG NEXT_PUBLIC_URL_ENCRYPT_KEY
# ARG NEXTAUTH_SECRET
ARG BACKEND_API_BASEURL
ARG FRONTEND_URL
ARG NEXTAUTH_URL

# Mengatur environment variables
ENV NEXT_PUBLIC_BACKEND_API_BASEURL=$NEXT_PUBLIC_BACKEND_API_BASEURL
ENV NEXT_PUBLIC_URL_PARAM_ENCRYPT_KEY=$NEXT_PUBLIC_URL_PARAM_ENCRYPT_KEY
ENV NEXT_PUBLIC_URL_ENCRYPT_KEY=$NEXT_PUBLIC_URL_ENCRYPT_KEY
# ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV BACKEND_API_BASEURL=$BACKEND_API_BASEURL
ENV FRONTEND_URL=$FRONTEND_URL
ENV NEXTAUTH_URL=$NEXTAUTH_URL

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Build the project
RUN npm run build

# Expose port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
