name: Deploy to VPS

on:
  push:
    branches:
      - "staging"

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear Next.js Cache
        run: npm cache clean --force

      - name: Set Environment Variables
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          BACKEND_API_BASEURL: ${{ secrets.BACKEND_API_BASEURL }}
          NEXT_PUBLIC_BACKEND_API_BASEURL: ${{ secrets.NEXT_PUBLIC_BACKEND_API_BASEURL }}
          NEXT_PUBLIC_URL_PARAM_ENCRYPT_KEY: ${{ secrets.NEXT_PUBLIC_URL_PARAM_ENCRYPT_KEY }}
          NEXT_PUBLIC_URL_ENCRYPT_KEY: ${{ secrets.DB_NAME }}
          NEXT_PUBLIC_GRECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_GRECAPTCHA_SITE_KEY }}
          GRECAPTCHA_SECRET_KEY: ${{ secrets.GRECAPTCHA_SECRET_KEY }}
          FRONTEND_URL: ${{ vars.FRONTEND_URL }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
        run: |
          echo "Environment variables set!"

      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pgapi_frontend:latest
          build-args: |
            NEXT_PUBLIC_BACKEND_API_BASEURL=${{ secrets.NEXT_PUBLIC_BACKEND_API_BASEURL }}
            NEXT_PUBLIC_URL_PARAM_ENCRYPT_KEY=${{ secrets.NEXT_PUBLIC_URL_PARAM_ENCRYPT_KEY }}
            NEXT_PUBLIC_URL_ENCRYPT_KEY=${{ secrets.NEXT_PUBLIC_URL_ENCRYPT_KEY }}
            BACKEND_API_BASEURL=${{ secrets.BACKEND_API_BASEURL }}
            NEXT_PUBLIC_GRECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_GRECAPTCHA_SITE_KEY }}
            GRECAPTCHA_SECRET_KEY=${{ secrets.GRECAPTCHA_SECRET_KEY }}
            FRONTEND_URL=${{ vars.FRONTEND_URL }}
            NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Stopping and removing previous container..."
            docker stop ${{ vars.CONTAINER_NAME }} || true && docker rm ${{ vars.CONTAINER_NAME }} || true
            echo "Pulling the latest image..."
            docker pull ${{ vars.IMAGE_NAME }}:latest
            echo "Running the container..."
            docker run -d \
              -p 3000:3000 \
              --name ${{ vars.CONTAINER_NAME }} \
              -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
              -e BACKEND_API_BASEURL=${{ secrets.BACKEND_API_BASEURL }} \
              -e NEXT_PUBLIC_BACKEND_API_BASEURL=${{ secrets.NEXT_PUBLIC_BACKEND_API_BASEURL }} \
              -e NEXT_PUBLIC_URL_PARAM_ENCRYPT_KEY=${{ secrets.NEXT_PUBLIC_URL_PARAM_ENCRYPT_KEY }} \
              -e NEXT_PUBLIC_URL_ENCRYPT_KEY=${{ secrets.NEXT_PUBLIC_URL_ENCRYPT_KEY }} \
              -e NEXT_PUBLIC_GRECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_GRECAPTCHA_SITE_KEY }} \
              -e GRECAPTCHA_SECRET_KEY=${{ secrets.GRECAPTCHA_SECRET_KEY }} \
              -e FRONTEND_URL=${{ vars.FRONTEND_URL }} \
              -e NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }} \
              ${{ vars.IMAGE_NAME }}:latest
            echo "Container started successfully!"
            echo "Debugging container environment variables..."
            sudo docker exec ${{ vars.CONTAINER_NAME }} env
